defaults: &defaults
  application:
    # indicate your external local address, example: http://192.168.100.50:3000
    url: "http://192.168.100.50:3000"
    host: "localhost:3000"
    domain: "demo.saltedge.com"
    name: "connector"
    title: "Demo Connector"
    private_key_path: 'test_private.pem'
  priora:
    base_url: "https://priora.saltedge.com"
    public_key_path: 'priora_public.pem'
  priora_app:
    # app_id and app_secret from Priora Dashboard
    app_id: "app_id"
    app_secret: "app_secret"
  priora_demo:
    base_url: "https://priora-demo.saltedge.com"

  # ===================== Application specific configuration =====================
  secret_key_base: "demo-secret-key" # used for signing emails https://github.com/rails/rails/blob/master/activesupport/lib/active_support/message_verifier.rb
  session_store: "_demo_session"     # key used for session_store: :cookie_store

# ===================== Environment based configuration =====================
development:
  <<: *defaults

test:
  <<: *defaults
  priora_demo:
    base_url: "https://google.com"

production:
  <<: *defaults

staging:
  <<: *defaults
